name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.8
  - seaborn=0.11.2
  - pandas=1.4.4
  - pip=22.2.2
  - pandas-profiling=3.3.0
  - pyarrow=9.0.0
  - pip:
      - wandb==0.13.3
