name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.29.0
  - ipython=8.5.0
  - notebook=6.4.12
  - jupyterlab=3.4.8
  - cookiecutter=2.1.1
  - hydra-core=1.2.0
  - matplotlib=3.5.3
  - pandas=1.4.4
  - gitpython=3.1.27
  - pip=22.2.2
  - pip:
      - wandb==0.13.3
