name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.4
  - pip=22.2.2
  - mlflow=1.29.0
  - scikit-learn=1.1.2
  - pip:
      - wandb==0.13.3
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
